### ISSUE TITLE
Using GECKO for HumanGEM

### ISSUE THREAD

**Issue by ezgitas** [SysBioChalmers/GECKO#129]
I am using GECKO to obtain the enzyme constraint HumanGEM model but most of the files are written for the saccharomyces cerevisiae model. I am having problems with adapting the toolbox to HumanGEM.

**Comment by BenjaSanchez** [comment]
@ezgitas hi there, thank you for showing interest in GECKO. I would recommend taking a look at the ecModels repository, where an enzyme-constrained model of humanGEM has already been developed. You can also see in general how we adapt the file structure to suit other organisms:

https://github.com/SysBioChalmers/ecModels/tree/feat/add_ecHumanGEM/ecHumanGEM

@IVANDOMENZAIN is this the latest version of ecHumanGEM?

**Comment by IVANDOMENZAIN** [comment]
Hi @ezgitas! you can find the latest version of the enzyme-constrained humanGEM in this [link](https://github.com/SysBioChalmers/ecModels/tree/feat/update_all_ecModels/ecHumanGEM/model). 

If you would like to generate cell-line specific or tissue-specific models for simulation purposes, then we recommend you to obtain those subset models first, by using some kind of gene expression data, and the tINIT algorithm available in the [RAVEN toolbox](https://github.com/SysBioChalmers/RAVEN). The next step would be to map your context-specific human model to ecHumanGEM in order to get your specific model with enzyme constraints, for this step we have generated a GECKO utility that gets this done in a matter of seconds, you can find it [here](https://github.com/SysBioChalmers/GECKO/blob/devel/geckomat/utilities/getSubset_ecModel.m).
