### ISSUE TITLE
Incorportate GECKO Light into the GECKO repo

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/GECKO#164]
GECKO Light does the following
1. Makes the model irreversible (same as original GECKO)
2. It penalizes each reaction with a protein cost that is MW/kcat
3. For complexes, the MWs are summed up
4. For isozymes, the lowest protein cost is used for the reaction. This is what the optimizer would select anyway.

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by edkerk** [comment]
Point 4 (isoenzymes) should still be addressed in #170, while the unit of MW/kcat is probably also not yet correct in that PR. Note that in generic GECKO, we'll redefine the enzyme usage fluxes as umol/gDW/h (instead of previously mmol/gDW/h), to prevent very low fluxes and issues with scaling when solving the LP.

**Comment by edkerk** [comment]
Implemented with #180.
