### ISSUE TITLE
ecModel independent on UniProt

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#203]
Would it be possible that one can build an ecModel without providing information that is needed to query UniProt?
I have a conventional GEM to test the ecModel reconstruction pipeline but the gene ids in the model do not match any gene id fields in UniProt. In other words, no results were found when searching in UniProt for gene ids of the model.
What is the solution?

**Comment by edkerk** [comment]
In the end uniprot is queried to generate the [`uniprot.tsv`](https://github.com/SysBioChalmers/GECKO/blob/devel3/userData/ecYeastGEM/data/uniprot.tsv) file, but if you manually construct this with the necessary content (and have it stored under `userData/***/data/uniprot.tsv` (if you want, we can also allow custom locations, this can be arranged in ModelAdapter if you wish)), it will not query Uniprot.

The content the file should have:
- Entry: Uniprot ID, can then be replaced by whatever identifier you prefer.
- Gene Names (ordered locus): should be the gene names used in the model
- Gene Names (primary): is actually never used, is for instance "Hxk1", therefore not necessary
- EC number: is only used when doing fuzzy matching to BRENDA, otherwise not necessary
- Mass: necessary
- Sequence: is only used when using DLKcat, otherwise not necessary

The columns that are not necessary should be empty, but still be there.

**Comment by feiranl** [comment]
I suppose if Uniprot file is not supplied, then DLkcat can also works?

**Comment by edkerk** [comment]
True, DLKcat itself can run. But `writeDLKcatInput` requires ´model.ec.sequences`, which are normally populated by `makeEcModel` that uses the Uniprot DB as input. You can also manually fill `model.ec.sequences`, or manually generate the input for DLKcat, but if you gather this information somewhere anyway, you might as well reformat it in a "fake" `uniprot.tsv` file, so that the common functions can be used.

This should be explained in the protocol, under Troubleshooting perhaps

**Comment by Yu-sysbio** [comment]
A relevant issue here: my test organism `Bacillus coagulans DSM 1 = ATCC 7050` is super special as there is no common gene identifier between UniProt and KEGG. Previously, the model used KEGG identifiers, as I had to query UniProt then I changed to UniProt gene identifiers. But now I get errors when running `getECfromDatabase(ecModel)`. 
I tried to skip getting EC from KEGG by setting `obj.params.keggGeneIdentifier = ''`, then I got errors below:

> Downloading KEGG data for organism code bcoa... 100% completeError using loadDatabases>downloadKEGG (line 161)
> None of the KEGG entries are annotated with
> 
> Error in loadDatabases (line 79)
>             downloadKEGG(keggID,keggPath,keggGeneIdentifier);
> 
> Error in getECfromDatabase (line 43)
> data    = loadDatabases('both', modelAdapter);
> 

How can users skip getting EC from KEGG?

**Comment by edkerk** [comment]
Good point, giving no KEGG organism id and not having a `kegg.tsv` file should just skip all KEGG steps.

Regarding:

> there is no common gene identifier between UniProt and KEGG.


Would it help to manually reconstruct either `uniprot.tsv` or `kegg.tsv`? Or is that what you've done?

**Comment by edkerk** [comment]
Ohw wait, I misunderstood. The organism is on KEGG, but the KEGG gene identifiers nor any additional "Other DBs" annotation are useful to match to your model? If you don't want to use any KEGG data for that purpose, you can just leave `obj.params.keggID` empty. I'm now changing that `obj.params.keggGeneIdentifier = ''` will be interpreted as `='kegg'`, so that by default it will still return the standard KEGG gene identifiers. But `getECfromDatabase` will then just not find any E.C. numbers from the KEGG data in your case, as the genes cannot be matched, so in that case you might as well not have gathered the KEGG data. OR, you manually edit `kegg.tsv` to convert the gene identifiers to what is used in your model. Good point to mention in Troubleshooting.

**Comment by edkerk** [comment]
The protocol now mentions what to do if KEGG or Uniprot data is missing.
