### ISSUE TITLE
doc: instructions for manual download

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#234]
There are a few steps where GECKO3 will automatically download some files, e.g., `runDLKcatFromDocker` and `findMetSmiles` (please check all). In case of poor internet connection or other errors with the failure of downloading, it would be better to display within the error where the users can manually download the required file(s) and then which path the downloaded file(s) should be saved. With this, the automatic file download can be skipped and the error can be addressed.

**Comment by edkerk** [comment]
Functions that can be documented for simple 1-URL download:
- `loadDatabases` for Uniprot: if functions gets a timeout, it now (eb9caabed6f0fcba7cc9ed0d5bdc9017e114587d) throws a warning with URL manually download.
- `runDLKcat`: `docker pull ghcr.io/sysbiochalmers/dlkcat-gecko:0.1`

Functions that cannot be documented for simple 1-URL download:
- `loadDatabases` for KEGG: first all genes are gathered, and then info for each gene is separately downloaded. Cannot be easily refactored without paid FTP access.
- `getComplexData`: function should be refactored to download tab-separated [files](http://ftp.ebi.ac.uk/pub/databases/intact/complex/current/complextab/), instead of querying the database for JSON.
- `findMetSmiles`: metabolites are queried one-by-one. I do not see how this can be simplified.

**Comment by mihai-sysbio** [comment]
Could some update if this was resolved, or what is left to do?

**Comment by mihai-sysbio** [comment]
I believe this issue now is fully addressed. Please reopen if otherwise.
