### ISSUE TITLE
Error in matching the custom Kcats

### ISSUE THREAD

**Issue by HossFir** [SysBioChalmers/GECKO#291]
There is an error in the following line:

https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/protocol.m#L116

I created the customKcats.tsv for my organism, trying to apply the customized Kcat to the ecModel, it showed the error:

Unrecognized function or variable 'kcatLast'.

Error in applyKcatConstraints (line 74)
https://github.com/SysBioChalmers/GECKO/blob/983c490bd2a0106e4db9603089c8b2482008f2a9/src/geckomat/change_model/applyKcatConstraints.m#L74

Error in applyCustomKcats (line 168)
https://github.com/SysBioChalmers/GECKO/blob/983c490bd2a0106e4db9603089c8b2482008f2a9/src/geckomat/change_model/applyCustomKcats.m#L168

However, this error was not raised for yeast!
I have the customKcats.tsv for my organism, but it could not match the ecModel!

**Comment by ae-tafur** [comment]
The error is caused because reaction `R537` have as GPR rule `sll1056 and slr0519 and slr0520` and in custom kcats you provided only `Q55843`, then this is not matching. Consider to put the info with the three proteins involved in the reaction or remove the protein info and just keep the rxn id, as follow: 

```

Q55843 + P72644 + Q55842  | slr0520 | purQ | 5.1 | R537 | GECKO v2 manual_data.txt | 1 + 1 + 1 

```

or 

```
  | slr0520 | purQ | 5.1 | R537 | GECKO v2 manual_data.txt | 1 + 1 + 1 
```

I tested this with the model you provided in #277 

In any case, this function needs to handled no any reaction match with the data in `customKcats.tsv`. I will fix this

**Comment by HossFir** [comment]
Nice, my issue was solved!
