### ISSUE TITLE
model with proteomics is overconstrained to reach maximum growth rate

### ISSUE THREAD

**Issue by ae-tafur** [SysBioChalmers/GECKO#296]
### Description of the bug:

After update prot_pool_exchange the maximum growth during `flexibilizeProtConcs` was 0.19142, experimental value is 0.419. `updateProtPool` reduce the prot_pool_exchange from -125 to -6. Omitting this step allow to reach the experimental growth rate 

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
More information would be appreciated here: what model is was this applied to? could you provide a brief description of the experiment? Also, if you know the PR/commit that introduced this bug, it would be great if you could link it here.

**Comment by edkerk** [comment]
To replicate this, can you please attach the ecModel and loaded modelAdapter as .mat files?

**Comment by ae-tafur** [comment]
I am attaching proteomics, flux data, ecModel, and adapter

[proteomics_integration.mat.zip](https://github.com/SysBioChalmers/GECKO/files/11028576/proteomics_integration.mat.zip)

**Comment by edkerk** [comment]
One can very easily overconstrain an ecModel that simulates maximum growth (= constraint by total protein content) *and* has proteomics data integrated. The enzyme content estimated by `updateProtPool` is then likely an underestimate, which indeed will not immediately result in a functional model. So this is a somewhat special case that cannot be simply resolved.

However, `flexibilizeProtConcs` does indicate that the protein pool LB is likely problematic and suggests to changes this. The underlying reason for this could be documented more clearly (in the function and protocol), but it is better to inform the user than to automatically release the LB to whatever is needed.

Todo: 
[ ] I noticed a bug in `updateProtPool` (which we encountered before but inadvertently failed to fix in #276), as it considers the f-factor twice when applying the new LB. I will fix this, but this will result in this case in an LB around -12 instead of -6 (and growth rate 0.26 is reached), so it does not resolve the bigger issue.

[ ] More detailed explanation in `flexibilizeProtConcs` (and Troubleshooting item in manuscript) on the risk of overconstraining the model with very high growth rate and proteomics data.

**Comment by ae-tafur** [comment]
I have three set of proteomics data, and in all them fails reaching the growth rate, in the other two cases, to reach 0.127, only reach 0.097, and to reach 0.171, only reach 0.13. 

A solution I propose is:

1. Not multiply `Ptot * f` in L72 `(updateProtPool)`
2. Calculate as `PdiffEnz = Ptot - PmeasEnz;`. Here, `setProtPoolSize` will take care of multiply this by f and sigma. It will results in `PdiffEnz` being around `256` (495-239, data above). Then LB, after  `setProtPoolSize`  will be around -67.84. With this value model, runs.

The problem I Identify with your approach is that your calculating the diff from ptot * f, which results in an small number and you only divide the diff / f

**Comment by edkerk** [comment]
#297 now has the suggested changes.

**Comment by HossFir** [comment]
I just wondered that until I use the protein pool for my organism, I give a more meaningful PPhP compared to the proteomics data integration. 

- The same constraints applied to both cases.
- The Kcats were modified for proteomics data integration according to GECKO reconstruction so that the approximate growth rate could be reached.

- Here is the case in the protein pool was defined (the photon uptake could reach 0): 
https://github.com/HossFir/Maud-Cyano/blob/main/Protein%20Pool.jpg

- Here is the case in the proteomics was integrated (the photon uptake could reach 122): 
https://github.com/HossFir/Maud-Cyano/blob/main/Proteomics.jpg
