### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/GECKO#311]
### Description of the bug:
As reported by the automated tests, data cannot be retrieved from Uniprot:

```
 Running geckoCoreFunctionTests
Downloading Uniprot data for taxonomy_id TE00000000. This can take a few minutes.

================================================================================
Error occurred in geckoCoreFunctionTests/testmakeEcModelFullModel_tc0001 and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using loadDatabases (line 64)
    Download failed, check your internet connection and try again, or manually download:
    https://rest.uniprot.org/uniprotkb/stream?query=reviewed:true+AND+taxonomy_id:TE00000000&fields=accession%252Cgene_tst%252Cec%252Cmass%252Csequence&format=tsv&compressed=false&sort=protein_name%2520asc
    
    Error in makeEcModel (line 141)
    uniprotDB = loadDatabases('both', modelAdapter);
```

#### Reproducing these results:
Trying out the Uniprot query manually indicates that the query parameters might have changed on the Uniprot side, since the response is:
```
Error messages
The 'taxonomy_id' filter value should be a number
Invalid fields parameter value 'accession%2Cgene_tst%2Cec%2Cmass%2Csequence'
Invalid sort parameter format. Expected format fieldName asc|desc.
```

#### System information
This is agnostic of the system.

**I hereby confirm that I have:**
- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by edkerk** [comment]
Did you make any other change to the `test` folder? `geckoCoreFunctionTests` is currently not written to test the download function of `loadDatabase`. Instead, when it is run as part of `testmakeEcModelFullModel_tc0001` it should find the `proteomics.tsv` file in `test/unit_tests/ecTestGEM/data` and continue to load that file, instead of calling Uniprot.

The `TE00000000` taxonomic ID is indeed not valid, but it should (currently) never been used for the above reason.

Instead, we should write a little test that uses a REAL taxonomic ID, perhaps find one with the smallest proteome so to minimize the number of actual proteins to be download and speeding up the test.

Bottom-line: the function is not the problem, the test setup is.

**Comment by johan-gson** [comment]
For now, could we just restore the test folder?

**Comment by mihai-sysbio** [comment]
Sorry about the mess - it was due to a bad path change on my part. It was resolved [here](https://github.com/SysBioChalmers/GECKO/pull/310#discussion_r1181024737).
